services:
  # PHP / Laravel app
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www/vt-tracker-api
    env_file:
      - .env

    networks:
      - laravel_network
    depends_on:
      - db

  # Nginx web server
  webserver:
    image: nginx:alpine
    container_name: laravel_web
    environment:
      - APP_URL=${APP_URL}
    depends_on:
      - app
    volumes:
      - ./vt-tracker-api:/var/www/vt-tracker-api
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "8000:80"
    networks:
      - laravel_network

  # PostgreSQL database
  db:
    image: postgres:15
    container_name: laravel_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel_network

# Network for all services
networks:
  laravel_network:

    # Persistent DB volume
volumes:
  db_data:
